# -*- coding: utf-8 -*-
"""LineCard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yi4uJIykLUaPaGyJQbm3HLJMDgAz8UL7
"""
# Imports
from airtable_utils import fetch_airtable_records
from pdf_generator import generate_pdf

def main():
  # Filter by region
  region = input("Enter the region (East, Midwest, North Central, Pacific Northwest, Rockies, Southwest, West): ")

  # Gets airtable records and sorts them into groups of parents and children companies w/ logos, and descriptions 
  airtable_records = fetch_airtable_records(region)

  generate_pdf(airtable_records, logo_path=f"assets/{region}Logo.jpg", output_path="output/line_card.pdf", region=region)
  print("PDF generated successfully at 'output/line_card.pdf'.")

if __name__ == "__main__":
  main()